import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = Path(os.getenv("BIKENGBAO_DATA_DIR", str(BASE_DIR / "data")))
UPLOAD_DIR = DATA_DIR / "uploads"
DB_PATH = DATA_DIR / "db.json"

HOST = os.getenv("BIKENGBAO_HOST", "127.0.0.1")
PORT = int(os.getenv("BIKENGBAO_PORT", "8787"))
MAX_UPLOAD_BYTES = int(os.getenv("BIKENGBAO_MAX_UPLOAD_BYTES", str(12 * 1024 * 1024)))

DATABASE_URL = os.getenv("DATABASE_URL", "")
DB_PROVIDER = os.getenv("BIKENGBAO_DB_PROVIDER", "postgres" if DATABASE_URL else "json")

FILE_STORAGE_PROVIDER = os.getenv(
    "BIKENGBAO_FILE_STORAGE_PROVIDER",
    "blob" if os.getenv("BLOB_READ_WRITE_TOKEN") else "local",
)
BLOB_READ_WRITE_TOKEN = os.getenv("BLOB_READ_WRITE_TOKEN", "")
BLOB_ACCESS = os.getenv("BIKENGBAO_BLOB_ACCESS", "public")

AI_PROVIDER = os.getenv("BIKENGBAO_AI_PROVIDER", "mock")
OCR_PROVIDER = os.getenv("BIKENGBAO_OCR_PROVIDER", "mock")
PAYMENT_PROVIDER = os.getenv("BIKENGBAO_PAYMENT_PROVIDER", "mock")
AUTH_PROVIDER = os.getenv("BIKENGBAO_AUTH_PROVIDER", "mock")

DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")
DEEPSEEK_BASE_URL = os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com")
DEEPSEEK_MODEL = os.getenv("DEEPSEEK_MODEL", "deepseek-chat")

WECHAT_APP_ID = os.getenv("WECHAT_APP_ID", "")
WECHAT_APP_SECRET = os.getenv("WECHAT_APP_SECRET", "")
WECHAT_MCH_ID = os.getenv("WECHAT_MCH_ID", "")
WECHAT_PAY_SERIAL_NO = os.getenv("WECHAT_PAY_SERIAL_NO", "")
WECHAT_PAY_PRIVATE_KEY = os.getenv("WECHAT_PAY_PRIVATE_KEY", "")
WECHAT_PAY_PRIVATE_KEY_PATH = os.getenv("WECHAT_PAY_PRIVATE_KEY_PATH", "")
WECHAT_PAY_API_V3_KEY = os.getenv("WECHAT_PAY_API_V3_KEY", "")
WECHAT_PAY_PLATFORM_CERT = os.getenv("WECHAT_PAY_PLATFORM_CERT", "")
WECHAT_PAY_PLATFORM_CERT_PATH = os.getenv("WECHAT_PAY_PLATFORM_CERT_PATH", "")
WECHAT_PAY_NOTIFY_URL = os.getenv("WECHAT_PAY_NOTIFY_URL", "")
WECHAT_PAY_API_BASE = os.getenv("WECHAT_PAY_API_BASE", "https://api.mch.weixin.qq.com")

ALIPAY_APP_ID = os.getenv("ALIPAY_APP_ID", "")
ALIPAY_APP_PRIVATE_KEY = os.getenv("ALIPAY_APP_PRIVATE_KEY", "")
ALIPAY_APP_PRIVATE_KEY_PATH = os.getenv("ALIPAY_APP_PRIVATE_KEY_PATH", "")
ALIPAY_PUBLIC_KEY = os.getenv("ALIPAY_PUBLIC_KEY", "")
ALIPAY_PUBLIC_KEY_PATH = os.getenv("ALIPAY_PUBLIC_KEY_PATH", "")
ALIPAY_GATEWAY = os.getenv("ALIPAY_GATEWAY", "https://openapi.alipay.com/gateway.do")
ALIPAY_NOTIFY_URL = os.getenv("ALIPAY_NOTIFY_URL", "")
ALIPAY_RETURN_URL = os.getenv("ALIPAY_RETURN_URL", "")

MANUAL_PAYMENT_QR_IMAGE_URL = os.getenv("MANUAL_PAYMENT_QR_IMAGE_URL", "")
MANUAL_PAYMENT_ACCOUNT_NAME = os.getenv("MANUAL_PAYMENT_ACCOUNT_NAME", "避坑宝运营")
MANUAL_PAYMENT_ACCOUNT_HINT = os.getenv("MANUAL_PAYMENT_ACCOUNT_HINT", "支付宝或微信收款码")
MANUAL_PAYMENT_NOTE_PREFIX = os.getenv("MANUAL_PAYMENT_NOTE_PREFIX", "BKB")
MANUAL_PAYMENT_EXPIRES_MINUTES = int(os.getenv("MANUAL_PAYMENT_EXPIRES_MINUTES", "30"))
BIKENGBAO_ADMIN_CONFIRM_TOKEN = os.getenv("BIKENGBAO_ADMIN_CONFIRM_TOKEN", "")

TENCENT_SECRET_ID = os.getenv("TENCENT_SECRET_ID", "")
TENCENT_SECRET_KEY = os.getenv("TENCENT_SECRET_KEY", "")
TENCENT_OCR_REGION = os.getenv("TENCENT_OCR_REGION", "ap-guangzhou")
TENCENT_OCR_ACTION = os.getenv("TENCENT_OCR_ACTION", "GeneralBasicOCR")
